api_platform:
    defaults:
        pagination_client_enabled: true
        pagination_items_per_page: '%lopi.pagination.items_per_page%'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    enable_swagger_ui: false
    enable_re_doc: false
    # metadata_backward_compatibility_layer: false

    # Metada about API
    title: 'Gift API'
    version: 'v1'
