api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Api/Entity']
        # types:
        #     Resource:
        #         abstract: true
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
