doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        dbname: gift_app
        host: localhost
        port: 5432
        user: gift_user
        password: root
        driver: 'pdo_pgsql'
        server_version: '13'
        charset: utf8

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            LopiApi:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'Lopi\Entity'
                alias: Lopi
