nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        # allow_headers: ['Content-Type', 'Authorization']
        allow_headers: ['Accept', 'Content-Type', 'Authorization', 'X-XSRF-TOKEN']
        expose_headers: ['Location', 'Set-Cookie']
        max_age: 3600
    paths:
        '^/': null
