controllers_api:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: /api

controllers_app:
    resource: ../../src/Controller/App
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
