controllers_api:
    resource: ../../src/Api/Controller/
    type: annotation
    prefix: /api

controllers_app:
    resource: ../../src/App/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
